apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkride-shuma-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: app-instance
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: app-instance
        app.kubernetes.io/name: app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      containers:
      - name: checkride-shuma-frontend
        image: default-route-openshift-image-registry.apps.687717108a3a4d1edcbc3cee.ap1.techzone.ibm.com/checkride-shuma-f/checkride-shuma-f:latest

        ports:
        - name: http
          protocol: TCP
          containerPort: 80
        env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        resources: {}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            port: http
            path: /
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            port: http
            path: /
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      imagePullSecrets:
      - name: sh-m-04-pull-secret
      securityContext: {}
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600